# Generated by Django 4.2.6 on 2023-10-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosVoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracao_segundos', models.PositiveSmallIntegerField()),
                ('volume_agua', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso_foguete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pressao_bomba', models.DecimalField(decimal_places=2, max_digits=6)),
                ('angulo_lancamento', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
