# Generated by Django 4.1 on 2023-11-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foguete", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eixo",
            fields=[
                ("idEixo", models.IntegerField(primary_key=True, serialize=False)),
                ("angulo", models.DecimalField(decimal_places=2, max_digits=4)),
                ("velocidade", models.DecimalField(decimal_places=2, max_digits=4)),
                ("aceleracao", models.DecimalField(decimal_places=2, max_digits=4)),
                ("tipoEixo", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Instante",
            fields=[
                ("idInstante", models.IntegerField(primary_key=True, serialize=False)),
                ("tempo", models.TimeField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("altitude", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="Voo",
            fields=[
                ("idVoo", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "volumeinicialAgua",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("pressaoInicial", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pesoFoguete", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pressaoBomba", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "anguloLancamento",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("duracaoSegundos", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="DadosVoo",
        ),
        migrations.AddField(
            model_name="instante",
            name="idVoo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foguete.voo"
            ),
        ),
        migrations.AddField(
            model_name="eixo",
            name="idInstante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="foguete.instante"
            ),
        ),
    ]
