# Generated by Django 4.1 on 2023-11-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foguete", "0002_eixo_instante_voo_delete_dadosvoo_instante_idvoo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Eixo",
        ),
    ]
