# Generated by Django 4.1 on 2023-11-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foguete", "0003_delete_eixo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voo",
            name="duracaoSegundos",
        ),
    ]
