# Generated by Django 4.1 on 2023-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foguete", "0004_remove_voo_duracaosegundos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voo",
            name="idVoo",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
